- name: "set ntp server for Astra Linux"
  hosts: astra
  gather_facts: false
  tasks:
    - name: "copy config"
      copy:
        src: /etc/systemd/timesyncd.conf
        dest: /etc/systemd/timesyncd.conf
        owner: root
        group: root
        mode: 0644

    - name: "enable timedatectl"
      shell: "sudo timedatectl set-ntp true"

    - name: "start timedatectl"
      shell: "sudo systemctl restart systemd-timesyncd"
